services:
  pg:
    container_name: hrms_db
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: hrms
      POSTGRES_USER: hrms_user
      POSTGRES_PASSWORD: hrms_pass
    ports:
      - "5332:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: