spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # === Employee Service ===
        - id: employee-service
          uri: ${EMPLOYEE_SERVICE_URL}
          predicates:
            - Path=/api/employees/**

        # === Department Service ===
        - id: department-service
          uri: ${DEPARTMENT_SERVICE_URL}
          predicates:
            - Path=/api/departments/**

        # === Leave Service ===
        - id: leave-service
          uri: ${LEAVE_SERVICE_URL}
          predicates:
            - Path=/api/leave-requests/**
            - Path=/api/leave-balances/**

        # === Auth Service ===
        - id: auth-service
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/api/auth/**

      globalcors:
        corsConfiguration:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

server:
  port: 8082
