spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: ${EMPLOYEE_SERVICE_URL}
          predicates:
            - Path=/api/employees/**

      globalcors:
        corsConfiguration:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

server:
  port: 8082
